version: '3.6'

networks:
  traveler-network:
    driver: bridge

services:
  traveler-api:
    build: .
    container_name: traveler-api
    command: yarn dev
    depends_on:
      - traveler-postgres
      - traveler-searcher
    environment:
      - POSTGRES_HOST=traveler-postgres
    volumes:
      - .:/home/node/api
    ports:
      - "3333:3333"
    networks:
      - traveler-network
    links:
      - traveler-postgres
      - traveler-searcher

  traveler-postgres-migrations:
    build: .
    container_name: traveler-postgres-migrations
    command: yarn typeorm migration:run
    depends_on:
      - traveler-postgres
    environment:
      - POSTGRES_HOST=traveler-postgres
    volumes:
      - .:/home/node/api
    networks:
      - traveler-network
    links:
      - traveler-postgres

  traveler-postgres:
    image: bitnami/postgresql:latest
    container_name: traveler-postgres
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    networks:
      - traveler-network

  traveler-searcher:
    image: valeriansaliou/sonic:v1.3.0
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
    networks:
      - traveler-network
    environment:
      - SECRET=${SONIC_PASSWORD}
